### ISSUE TITLE
Enlaces rotos en README

### ISSUE THREAD

**Issue by Beelzenef** [JasrSir/CuadernoClase#1]
Los enlaces a imágenes que son screenshots en el README no son visibles, en caso de necesitar visitar esos recursos en el futuro no sería posible.

:camera_flash: :keyboard:

**Comment by JasrSir** [comment]
Muchas gracias por tu comentario usuaria/compañera.
Debo comunicarte que esas capturas están en el repositorio de bitbucket, en el cual no hay ningun problema.

Un afectuoso saludo Beelzenef
